### ISSUE TITLE
Accordion - Front-end

### ISSUE THREAD

**Issue by vladimirdacosta** [GemeenteNijmegen/component-library#111]
**Doel**
Het doel van dit issue is om het Accordeon-component te bouwen, zodat gebruikers inhoud kunnen organiseren en bekijken in een opvouwbare en uitvouwbare indeling.

**Beschrijving**
Het Accordeon-component helpt gebruikers om informatie overzichtelijk te tonen door secties in en uit te vouwen. Het frontend-team moet dit ontwerp omzetten in werkende code die gemakkelijk te gebruiken is.

**Acceptatiecriteria (Acc):**

- Het Accordeon-component moet werken zoals beschreven in het ontwerp.
- Gebruikers moeten secties kunnen in- en uitvouwen door erop te klikken.
- Het component moet goed werken op verschillende schermformaten en apparaten.
- Het component moet toegankelijk zijn, inclusief ondersteuning voor toetsenbordbediening en duidelijke visuele aanwijzingen.
- Het component moet goed getest zijn en zonder fouten werken.

**Definitie van 'Done' (DoD):**

- Het Accordeon-component is gebouwd en geïntegreerd in de componentbibliotheek.
- Het component werkt goed op verschillende schermformaten en apparaten.
- Het component voldoet aan alle acceptatiecriteria, inclusief toegankelijkheidseisen.
- Eventuele bugs zijn opgelost.
- Het Accordeon-component is gereed voor technisch review en klaar voor gebruik in de productieomgeving.

Link naar het ontwerp: https://www.figma.com/design/g3AieWAFD3NtkbDDTTFC30/Novio---Nijmegen-Design-System?node-id=6537-8646

**Comment by Michel-Verhoeven** [comment]
[Hier te testen](https://wowebnl.github.io/design-system-nijmegen/?path=/docs/react-accordion--docs)

**Comment by Rozerinay** [comment]
@Michel-Verhoeven ziet er goed uit!

Ik zie alleen dat de border-block-end-width ontbreekt bij de __section.

Het gaat specifiek om deze tokens:

- `todo.accordion.section.border-block-end-width`
- `todo.accordion.section.border-color`

**Comment by vladimirdacosta** [comment]
@Michel-Verhoeven nog tijd gehad om naar de feedback van Rozerin te checken ?

**Comment by MariannevanLierop** [comment]
@joostvanderborg zou jij de Accordion willen testen?

**Comment by joostvanderborg** [comment]
Een opmerking: In tegenstelling tot andere implementaties zie ik dat de cursor bij ons geen indicatie geeft van klikbaarheid. Ik vermoed door standaard-gedrag van buttons, maar qua consistentie met anderen zou mijn voorkeur hebben dat deze een indicatie geeft. 
Zie:
- https://designsystem.amsterdam/?path=/docs/components-containers-accordion--docs
- https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-accordion--docs
- https://nl-design-system.github.io/rvo/?path=/docs/componenten-accordion--documentatie

Nb: RVO gebruikt een andere HTML-structuur (details + summary). Overigens ben ik daar qua html-gebruik wel van gecharmeerd, maar da's qua implementatie vermoedelijk wel wat scope-creep ;).

**Comment by vladimirdacosta** [comment]
@joostvanderborg  Helemaal eens, ik snap precies wat je bedoelt.
@mwbankers87   Ik mis hier nog de border-block-end-width bij de __section.

**Comment by Michel-Verhoeven** [comment]
@mwbankers87 zie commentaren van Joost en Vladimir

**Comment by mwbankers87** [comment]
@Rozerinay @vladimirdacosta 

Ik ben er even ingedoken. Dit component is rechtstreeks overgenomen van de React versie van Utrecht. Volgens mij had Utrecht nog geen borders toen ik er destijds mee bezig was. Ik zag dat ze deze inmiddels wel hebben, dus ik heb de package naar de laatste versie gebracht.

Hier zit wel de juiste css in voor de borders, echter zijn deze tokens niet gezet, zie code hieronder. Ik wilde bij deze dus even overleggen wat hier verstandig is om te doen. Want het lijkt me dat als deze tokens juist gezet worden, dat het werkt.

```scss
.utrecht-accordion__section:is(:last-child, :only-child) {
  border-block-end-color: var(--utrecht-accordion-section-border-color,currentColor);
  border-block-end-style: solid;
  border-block-end-width: var(--utrecht-accordion-section-border-width,0);
}

.utrecht-accordion__section {
  border-block-start-color: var(--utrecht-accordion-section-border-color,currentColor);
  border-block-start-style: solid;
  border-block-start-width: var(--utrecht-accordion-section-border-width,0);
  break-inside: avoid;
}
```
